ai:
  api_key: your_openai_api_key_here
  max_tokens: 2000
  model: gpt-4
  temperature: 0.3
general:
  log_level: INFO
  max_scan_timeout: 300
  output_dir: output
output:
  compress_old: true
  save_analysis: true
  save_parsed: true
  save_raw: true
tools:
  bbot:
    default_flags:
    - subdomain-enum
    enabled: true
    timeout: 300
  spiderfoot:
    base_url: http://localhost:5001
    enabled: false
    timeout: 600
